In [1]:
t = 'abc',12345,23.54
t

('abc', 12345, 23.54)

In [2]:
name, id, dph = t

In [3]:
name
id
dph


23.54

In [4]:
name

'abc'

In [5]:
id

12345

In [6]:
id = 55555
id


55555

In [7]:
t = name, id, dph
t

('abc', 55555, 23.54)

In [9]:
x, y, _ = t
x

'abc'

In [10]:
_

23.54

In [22]:
from collections import namedtuple
EmployeeRecord = namedtuple('EmployeeRecord','name,age,dept,pay')
import csv
for emp in map(EmployeeRecord._make, csv.reader(open("C:\\Users\\AW954XQ\\employees.csv", "r"))):
    print(emp.name, emp.dept, emp.pay)

name dept pay
sam IT 200000
pam IT 100000
tam sales 150000
jam finance 75000


In [23]:
(1, 2, 3)              < (1, 2, 4)

True

In [24]:
(1,2,3) == [1,2,3]

False

In [25]:
[1,2,4] > [1,2,2]

True

In [26]:
'ABC' < 'C' < 'Pascal' < 'Python'

True

In [27]:
'ABC' < 'C'

True

In [28]:
(1, 2, 3)             == (1.0, 2.0, 3.0)

True

In [29]:
my_string="ANALYTICS VIDHYA"
my_string[::-1]

'AYHDIV SCITYLANA'

In [30]:
my_list = ['lakshay','sanad','aravind','aishwarya','prateek']
find_a = []
for name in my_list:
    x = name.find('a')
    find_a.append(x)
find_a    
                  

[1, 1, 0, 0, 2]

In [33]:
state = ['haryana','punjab','rajasthan','karnataka','goa']
output = []
for s in state:
    split_at_a = s.split('a')
    print(split_at_a)
    output.append(len(split_at_a))
output    
    

['h', 'ry', 'n', '']
['punj', 'b']
['r', 'j', 'sth', 'n']
['k', 'rn', 't', 'k', '']
['go', '']


[4, 2, 4, 5, 2]

In [37]:
62//10==6

True

In [5]:
y = lambda x : x+10
print(y(2))

12


In [ ]:
y = def f1(x):
        x+10

In [ ]:
y = def f1(x):
        x+10

In [8]:
def find_number_handshakes(n):
    print("Value of n: ", n)
    if n == 2:
        
        return 1
    else:
 
        temp_result = find_number_handshakes(n - 1) + (n - 1)
        print("Temporary result is : ", temp_result)
        return find_number_handshakes(n-1) + (n-1)

result = find_number_handshakes(4)
print(result)

Value of n:  4
Value of n:  3
Value of n:  2
Temporary result is :  3
Value of n:  2
Temporary result is :  6
Value of n:  3
Value of n:  2
Temporary result is :  3
Value of n:  2
6


In [25]:
def find_number_handshakes(n):
    print("Value of n: ", n)
    if n == 2:
        
        return 1
    else:
 
        temp_result = find_number_handshakes(n - 1) + (n + 1)
        print("Temporary result is : ", temp_result)
        return find_number_handshakes(n-1) + (n+1)

result = find_number_handshakes(5)
print(result)

Value of n:  5
Value of n:  4
Value of n:  3
Value of n:  2
Temporary result is :  5
Value of n:  2
Temporary result is :  10
Value of n:  3
Value of n:  2
Temporary result is :  5
Value of n:  2
Temporary result is :  16
Value of n:  4
Value of n:  3
Value of n:  2
Temporary result is :  5
Value of n:  2
Temporary result is :  10
Value of n:  3
Value of n:  2
Temporary result is :  5
Value of n:  2
16


In [23]:
def function(number):
    if number == 1:
        return 0
    elif number == 2:
        return 1
    else:
        return function(number - 1) + function(number - 2)
function(5)        

3

In [15]:
file = open("emp.txt", "r")
content = file.read()
content

'1001, Test1, 120000, 9999\n1002, Test2, 145000, 8888\n1003, Test3, 210000, 5555'

In [21]:
content = file.read()
content

'1, 120000, 9999\n1002, Test2, 145000, 8888\n1003, Test3, 210000, 5555'

In [32]:
file.close()

In [20]:
file.seek(10)

10

In [31]:
file = open("emp.txt", "r")
contents = file.readlines()
for content in contents:
    print(content)

1001, Test1, 120000, 9999

1002, Test2, 145000, 8888

1003, Test3, 210000, 5555


In [35]:
with open("emp.txt", "r") as file:
    contents = file.readlines()
contents    

['1001, Test1, 120000, 9999\n',
 '1002, Test2, 145000, 8888\n',
 '1003, Test3, 210000, 5555']

In [37]:
new_contents = open("new_file.txt", "w+")
new_contents.write("This is first line written")

26

In [39]:
list_contents = ["This is second line written\n", "This is third line written\n", "This is fourth line written\n"]
new_contents = open("new_file.txt", "w+")
new_contents.writelines(list_contents)

In [44]:
list_contents = ["This is fifth line written\n", "This is sixth line written\n", "This is seventh line written\n"]
new_contents = open("new_file.txt", "a+")
new_contents.writelines(list_contents)

In [45]:
with open("new_file.txt") as f:
    contents = f.readlines()
contents    

['This is second line written\n',
 'This is third line written\n',
 'This is fourth line written\n',
 'This is fifth line written\n',
 'This is sixth line written\n',
 'This is seventh line written\n']

In [46]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [10]:
import numpy as np

In [48]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [49]:
arry1 = np.array([1,2,3,4,5,6])
arry1

array([1, 2, 3, 4, 5, 6])

In [50]:
arry1 * 2

array([ 2,  4,  6,  8, 10, 12])

In [51]:
matrix_1 = [[1,2,3],[4,5,6],[7,8,9]]
np_matrix = np.array(matrix_1)
np_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
np_matrix[1][2]

6

In [53]:
np_matrix[1]

array([4, 5, 6])

In [54]:
np.random.randint(0,10, (3,3))

array([[3, 1, 3],
       [2, 0, 2],
       [7, 8, 8]])

In [56]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [57]:
np.ones((4,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [58]:
np.identity(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [59]:
np.full((3,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [13]:
a_m = [[1,2,3],[4,5,6]]
b_m = [[7,8,9],[10,11,12]]
np.concatenate([a_m,b_m], axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [66]:
import scipy

In [67]:
scipy.__version__

'1.11.4'

In [16]:
from scipy.misc import derivative
def my_f(x):
    return x**2 + 5
derivative(func=my_f, x0=2)    

C:\Users\AW954XQ\AppData\Local\Temp\ipykernel_17720\3158201914.py:4: DeprecationWarning: scipy.misc.derivative is deprecated in SciPy v1.10.0; and will be completely removed in SciPy v1.12.0. You may consider using findiff: https://github.com/maroba/findiff or numdifftools: https://github.com/pbrod/numdifftools
  derivative(func=my_f, x0=2)


4.0

In [17]:
import pandas as pd

In [18]:
pd.__version__

'2.1.4'

In [19]:
big_mart_sales_data = pd.read_csv("big_mart_sales.csv")
big_mart_sales_data

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0              FDA15        9.300          Low Fat         0.016047   
1              DRC01        5.920          Regular         0.019278   
2              FDN15       17.500          Low Fat         0.016760   
3              FDX07       19.200          Regular         0.000000   
4              NCD19        8.930          Low Fat         0.000000   
...              ...          ...              ...              ...   
8518           FDF22        6.865          Low Fat         0.056783   
8519           FDS36        8.380          Regular         0.046982   
8520           NCJ29       10.600          Low Fat         0.035186   
8521           FDN46        7.210          Regular         0.145221   
8522           DRG01       14.800          Low Fat         0.044878   

                  Item_Type  Item_MRP Outlet_Identifier  \
0                     Dairy  249.8092            OUT049   
1               Soft Drinks   48.2692            OUT018   
2                      Meat  141.6180            OUT049   
3     Fruits and Vegetables  182.0950            OUT010   
4                 Household   53.8614            OUT013   
...                     ...       ...               ...   
8518            Snack Foods  214.5218            OUT013   
8519           Baking Goods  108.1570            OUT045   
8520     Health and Hygiene   85.1224            OUT035   
8521            Snack Foods  103.1332            OUT018   
8522            Soft Drinks   75.4670            OUT046   

      Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                          1999      Medium               Tier 1   
1                          2009      Medium               Tier 3   
2                          1999      Medium               Tier 1   
3                          1998         NaN               Tier 3   
4                          1987        High               Tier 3   
...                         ...         ...                  ...   
8518                       1987        High               Tier 3   
8519                       2002         NaN               Tier 2   
8520                       2004       Small               Tier 2   
8521                       2009      Medium               Tier 3   
8522                       1997       Small               Tier 1   

            Outlet_Type  Item_Outlet_Sales  
0     Supermarket Type1          3735.1380  
1     Supermarket Type2           443.4228  
2     Supermarket Type1          2097.2700  
3         Grocery Store           732.3800  
4     Supermarket Type1           994.7052  
...                 ...                ...  
8518  Supermarket Type1          2778.3834  
8519  Supermarket Type1           549.2850  
8520  Supermarket Type1          1193.1136  
8521  Supermarket Type2          1845.5976  
8522  Supermarket Type1           765.6700  

[8523 rows x 12 columns]

In [32]:
big_mart_sales_data.shape

(8523, 12)

In [21]:
big_mart_sales_data.head(5)

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15         9.30          Low Fat         0.016047   
1           DRC01         5.92          Regular         0.019278   
2           FDN15        17.50          Low Fat         0.016760   
3           FDX07        19.20          Regular         0.000000   
4           NCD19         8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998         NaN               Tier 3   
4                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

In [34]:
big_mart_sales_data.columns

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Item_Outlet_Sales'],
      dtype='object')

In [30]:
big_mart_sales_data.describe()

Item_Weight  Item_Visibility     Item_MRP  Outlet_Establishment_Year  \
count  7060.000000      8523.000000  8523.000000                8523.000000   
mean     12.857645         0.066132   140.992782                1997.831867   
std       4.643456         0.051598    62.275067                   8.371760   
min       4.555000         0.000000    31.290000                1985.000000   
25%       8.773750         0.026989    93.826500                1987.000000   
50%      12.600000         0.053931   143.012800                1999.000000   
75%      16.850000         0.094585   185.643700                2004.000000   
max      21.350000         0.328391   266.888400                2009.000000   

       Item_Outlet_Sales  
count        8523.000000  
mean         2181.288914  
std          1706.499616  
min            33.290000  
25%           834.247400  
50%          1794.331000  
75%          3101.296400  
max         13086.964800

In [39]:
big_mart_sales_data.isna().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [36]:
big_mart_sales_data.dtypes

Item_Identifier               object
Item_Weight                  float64
Item_Fat_Content              object
Item_Visibility              float64
Item_Type                     object
Item_MRP                     float64
Outlet_Identifier             object
Outlet_Establishment_Year      int64
Outlet_Size                   object
Outlet_Location_Type          object
Outlet_Type                   object
Item_Outlet_Sales            float64
dtype: object

In [41]:
big_mart_sales_data.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [42]:
import sklearn

In [43]:
sklearn.__version__

'1.2.2'

In [1]:
l1 = [1,2,3,4,5,6]
l1

[1, 2, 3, 4, 5, 6]

In [2]:
l1[2:4]

[3, 4]

In [3]:
l1

[1, 2, 3, 4, 5, 6]

In [5]:
import numpy as np
a1 = np.array([1,2,3,4,5,6])
a1

array([1, 2, 3, 4, 5, 6])

In [6]:
a1[2:4]

array([3, 4])

In [7]:
a1

array([1, 2, 3, 4, 5, 6])

In [9]:
l1_1 = l1[2:4]
l1_1

[3, 4]

In [11]:
l1_1[0]=33
l1_1

[33, 4]

In [12]:
l1

[1, 2, 3, 4, 5, 6]

In [14]:
a1 = np.array([1,2,3,4,5,6])
a1

array([1, 2, 3, 4, 5, 6])

In [15]:
a1_1=a1[2:4]
a1_1

array([3, 4])

In [16]:
a1_1[0]=33
a1_1

array([33,  4])

In [17]:
a1

array([ 1,  2, 33,  4,  5,  6])

In [19]:
a1.ndim

1

In [20]:
a1.shape

(6,)

In [21]:
len(a1.shape)==a1.ndim

True

In [22]:
a1.size

6

In [26]:
np.empty((2,3),dtype=float)

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.39074501e-307, 3.78292434e-307, 1.05699581e-307]])

In [28]:
np.arange(5,10,2)

array([5, 7, 9])

In [38]:
np.linspace(0,10,num=10,dtype=float)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [39]:
np.sort(a1)

array([ 1,  2,  4,  5,  6, 33])

In [40]:
x = np.array([[0, 3], [2, 2]])
x

array([[0, 3],
       [2, 2]])

In [53]:
ind = np.argsort(x, axis=0)
ind


array([[0, 1],
       [1, 0]], dtype=int64)

In [54]:
a2 = x[ind]
a2

array([[[0, 3],
        [2, 2]],

       [[2, 2],
        [0, 3]]])

In [50]:
array = np.array([10, 3, 5, 6, 2])
sorted_indices = np.argsort(array)
print("Original array:", array)
print("Indices that would sort the array:", sorted_indices)
sorted_array = array[sorted_indices]
print("Sorted array:", sorted_array)

Original array: [10  3  5  6  2]
Indices that would sort the array: [4 1 2 3 0]
Sorted array: [ 2  3  5  6 10]


In [56]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [57]:
a2 = a[np.newaxis, :]
a2

array([[1, 2, 3, 4, 5, 6]])

In [58]:
a2.shape

(1, 6)

In [60]:
a3 = a[:, np.newaxis]
a3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [2]:
import numpy as np

In [3]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
a[a<5]

array([1, 2, 3, 4])

In [63]:
five_up = a >=5
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [64]:
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
c = a[(a>3) & (a<10)]
c

array([4, 5, 6, 7, 8, 9])

In [7]:
print(np.nonzero(a <= 5))

(array([0, 0, 0, 0, 1], dtype=int64), array([0, 1, 2, 3, 0], dtype=int64))


In [6]:
print(np.nonzero(c<5))

(array([0], dtype=int64),)


In [8]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [10]:
print(b.sum(axis=0))

[3 3]


In [11]:
print(b.sum(axis=1))

[2 4]


In [12]:
import pandas as pd

In [13]:
df = pd.DataFrame (
    {
        "Name" : 
            ["Sam", "Pam", "Tam"],
        "Age" :
            [32, 45, 12],
        "Sex" :
            ["male", "female", "female"]
    }
)
df

Name  Age     Sex
0  Sam   32    male
1  Pam   45  female
2  Tam   12  female

In [15]:
df

Name  Age     Sex
0  Sam   32    male
1  Pam   45  female
2  Tam   12  female

In [16]:
df["Name"]

0    Sam
1    Pam
2    Tam
Name: Name, dtype: object

In [17]:
df["Age"]

0    32
1    45
2    12
Name: Age, dtype: int64

In [19]:
loc = pd.Series(["Atlanta", "Georgia", "Georgia"], name="Location")

In [20]:
df

Name  Age     Sex
0  Sam   32    male
1  Pam   45  female
2  Tam   12  female

In [21]:
loc

0    Atlanta
1    Georgia
2    Georgia
Name: Location, dtype: object

In [26]:
df["Location"] = loc
df

Name  Age     Sex Location
0  Sam   32    male  Atlanta
1  Pam   45  female  Georgia
2  Tam   12  female  Georgia

In [27]:
df

Name  Age     Sex Location
0  Sam   32    male  Atlanta
1  Pam   45  female  Georgia
2  Tam   12  female  Georgia

In [28]:
df.insert(0, "Salutation", ["Dr", "Dr", "Ms"], True)
df

Salutation Name  Age     Sex Location
0         Dr  Sam   32    male  Atlanta
1         Dr  Pam   45  female  Georgia
2         Ms  Tam   12  female  Georgia

In [29]:
df["Marital Status"] = ["Divorced", "Divorced", "Single"]
df

Salutation Name  Age     Sex Location Marital Status
0         Dr  Sam   32    male  Atlanta       Divorced
1         Dr  Pam   45  female  Georgia       Divorced
2         Ms  Tam   12  female  Georgia         Single

In [37]:
df1= df.assign(Phone=["1111111", "2222222", "3333333"])
df1

Salutation Name  Age     Sex Location Marital Status    Phone
0         Dr  Sam   32    male  Atlanta       Divorced  1111111
1         Dr  Pam   45  female  Georgia       Divorced  2222222
2         Ms  Tam   12  female  Georgia         Single  3333333

In [33]:
df

Salutation Name  Age     Sex Location Marital Status
0         Dr  Sam   32    male  Atlanta       Divorced
1         Dr  Pam   45  female  Georgia       Divorced
2         Ms  Tam   12  female  Georgia         Single

In [34]:
email = pd.Series(["xyz@gmail.com", "yxz@yahoo.com", "aaa@gmail.com"], name="Email")

In [137]:
df2 = df1.assign(Email = email)
df2

Salutation Name  Age     Sex Location Marital Status    Phone          Email
0         Dr  Sam   32    male  Atlanta       Divorced  1111111  xyz@gmail.com
1         Dr  Pam   45  female  Georgia       Divorced  2222222  yxz@yahoo.com
2         Ms  Tam   12  female  Georgia         Single  3333333  aaa@gmail.com

In [45]:
df2["Age"].max()

45

In [67]:
df2.loc[df2["Age"].idxmin()]

Salutation                   Ms
Name                        Tam
Age                          12
Sex                      female
Location                Georgia
Marital Status           Single
Phone                   3333333
Email             aaa@gmail.com
Name: Row3, dtype: object

In [50]:
df2.columns

Index(['Salutation', 'Name', 'Age', 'Sex', 'Location', 'Marital Status',
       'Phone', 'Email'],
      dtype='object')

In [51]:
df2.index

RangeIndex(start=0, stop=3, step=1)

In [53]:
df2.columns[0]

'Salutation'

In [54]:
df2.index = ["Row1", "Row2", "Row3"]

In [55]:
df2

Salutation Name  Age     Sex Location Marital Status    Phone  \
Row1         Dr  Sam   32    male  Atlanta       Divorced  1111111   
Row2         Dr  Pam   45  female  Georgia       Divorced  2222222   
Row3         Ms  Tam   12  female  Georgia         Single  3333333   

              Email  
Row1  xyz@gmail.com  
Row2  yxz@yahoo.com  
Row3  aaa@gmail.com

In [58]:
df2.to_numpy(copy=True)

array([['Dr', 'Sam', 32, 'male', 'Atlanta', 'Divorced', '1111111',
        'xyz@gmail.com'],
       ['Dr', 'Pam', 45, 'female', 'Georgia', 'Divorced', '2222222',
        'yxz@yahoo.com'],
       ['Ms', 'Tam', 12, 'female', 'Georgia', 'Single', '3333333',
        'aaa@gmail.com']], dtype=object)

In [57]:
df2.values

array([['Dr', 'Sam', 32, 'male', 'Atlanta', 'Divorced', '1111111',
        'xyz@gmail.com'],
       ['Dr', 'Pam', 45, 'female', 'Georgia', 'Divorced', '2222222',
        'yxz@yahoo.com'],
       ['Ms', 'Tam', 12, 'female', 'Georgia', 'Single', '3333333',
        'aaa@gmail.com']], dtype=object)

In [59]:
df2.dtypes

Salutation        object
Name              object
Age                int64
Sex               object
Location          object
Marital Status    object
Phone             object
Email             object
dtype: object

In [68]:
df2.ndim

2

In [69]:
df2.shape

(3, 8)

In [70]:
df2.size

24

In [73]:
df2.memory_usage(index=False)

Salutation        24
Name              24
Age               24
Sex               24
Location          24
Marital Status    24
Phone             24
Email             24
dtype: int64

In [75]:
df2["Name"]

Row1    Sam
Row2    Pam
Row3    Tam
Name: Name, dtype: object

In [76]:
df2.loc["Row2"]

Salutation                   Dr
Name                        Pam
Age                          45
Sex                      female
Location                Georgia
Marital Status         Divorced
Phone                   2222222
Email             yxz@yahoo.com
Name: Row2, dtype: object

In [77]:
df2.iloc[1]

Salutation                   Dr
Name                        Pam
Age                          45
Sex                      female
Location                Georgia
Marital Status         Divorced
Phone                   2222222
Email             yxz@yahoo.com
Name: Row2, dtype: object

In [81]:
df2

Salutation Name  Age     Sex Location Marital Status    Phone  \
Row1         Dr  Sam   32    male  Atlanta       Divorced  1111111   
Row2         Dr  Pam   45  female  Georgia       Divorced  2222222   
Row3         Ms  Tam   12  female  Georgia         Single  3333333   

              Email  
Row1  xyz@gmail.com  
Row2  yxz@yahoo.com  
Row3  aaa@gmail.com

In [82]:
df2.loc["Row2"]

Salutation                   Dr
Name                        Pam
Age                          45
Sex                      female
Location                Georgia
Marital Status         Divorced
Phone                   2222222
Email             yxz@yahoo.com
Name: Row2, dtype: object

In [84]:
df2.loc[:,"Name"]

Row1    Sam
Row2    Pam
Row3    Tam
Name: Name, dtype: object

In [86]:
df2.loc["Row2",["Name","Age"]]

Name    Pam
Age      45
Name: Row2, dtype: object

In [88]:
df2.iloc[1,1]

'Pam'

In [90]:
df2.at["Row2","Name"]

'Pam'

In [94]:
df2.loc[["Row1", "Row2"],["Name","Age"]]

Name  Age
Row1  Sam   32
Row2  Pam   45

In [95]:
df

Salutation Name  Age     Sex Location Marital Status
0         Dr  Sam   32    male  Atlanta       Divorced
1         Dr  Pam   45  female  Georgia       Divorced
2         Ms  Tam   12  female  Georgia         Single

In [97]:
df.loc[0:1,["Name","Age"]]

Name  Age
0  Sam   32
1  Pam   45

In [100]:
df.iloc[0:2,[1,2]]

Name  Age
0  Sam   32
1  Pam   45

In [106]:
df2.loc[:, DummyColumn] = [1,2,3]

In [107]:
df2

Salutation Name  Age     Sex Location Marital Status    Phone  \
Row1         Dr  Sam   32    male  Atlanta       Divorced  1111111   
Row2         Dr  Pam   45  female  Georgia       Divorced  2222222   
Row3         Ms  Tam   12  female  Georgia         Single  3333333   

              Email  1  2  3  
Row1  xyz@gmail.com  1  2  3  
Row2  yxz@yahoo.com  1  2  3  
Row3  aaa@gmail.com  1  2  3

In [108]:
import pandas as pd

# Creating a sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'Sex': ['F', 'M', 'M', 'M']
}

df = pd.DataFrame(data)

# Suppose we want to set the age of 'Charlie' to 36

# This might raise a SettingWithCopyWarning
subset = df[df['Name'] == 'Charlie']
subset['Age'] = 36
print(df)

# Recommended way to avoid SettingWithCopyWarning
df.loc[df['Name'] == 'Charlie', 'Age'] = 36
print(df)


      Name  Age Sex
0    Alice   25   F
1      Bob   30   M
2  Charlie   35   M
3    David   40   M
      Name  Age Sex
0    Alice   25   F
1      Bob   30   M
2  Charlie   36   M
3    David   40   M


C:\Users\AW954XQ\AppData\Local\Temp\ipykernel_7408\519490853.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset['Age'] = 36


In [119]:
df2[df2["Age"]== df2["Age"].max()]

Salutation Name  Age   Sex Location Marital Status    Phone          Email
0         Dr  Sam   32  male  Atlanta       Divorced  1111111  xyz@gmail.com

In [111]:
df2["Age"]== df2["Age"].max()

Row1    False
Row2     True
Row3    False
Name: Age, dtype: bool

In [112]:
df2.loc[df2["Age"] == df2["Age"].max()] = 31

In [115]:
df2

Salutation Name  Age     Sex Location Marital Status    Phone          Email
0         Dr  Sam   32    male  Atlanta       Divorced  1111111  xyz@gmail.com
1         Dr  Pam   45  female  Georgia       Divorced  2222222  yxz@yahoo.com
2         Ms  Tam   12  female  Georgia         Single  3333333  aaa@gmail.com

In [117]:
df2.loc[df2["Age"] == df2["Age"].max(),"Age"] =31

In [126]:
df2

Salutation Name  Age     Sex Location Marital Status    Phone          Email
0         Dr  Sam   32    male  Atlanta       Divorced  1111111  xyz@gmail.com
1         Dr  Pam   31  female  Georgia       Divorced  2222222  yxz@yahoo.com
2         Ms  Tam   12  female  Georgia         Single  3333333  aaa@gmail.com

In [120]:
df2[df2["Age"] == df2["Age"].max()]["Age"]=30

C:\Users\AW954XQ\AppData\Local\Temp\ipykernel_7408\649109824.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[df2["Age"] == df2["Age"].max()]["Age"]=30


In [141]:
newuser = {"Salutation": "Mr", "Name": "Jam", "Age": 45, "Sex": "male", "Location": "New Jersey", "Marital Status": "Married", "Phone": 99999, "Email": "jammy@gamil.com"}
newuser
df2 = pd.concat([df2,pd.DataFrame([newuser])],ignore_index=True)
df2

Salutation Name  Age     Sex    Location Marital Status    Phone  \
0         Dr  Sam   32    male     Atlanta       Divorced  1111111   
1         Dr  Pam   45  female     Georgia       Divorced  2222222   
2         Ms  Tam   12  female     Georgia         Single  3333333   
3         Mr  Jam   45    male  New Jersey        Married    99999   
4         Mr  Jam   45    male  New Jersey        Married    99999   

             Email  
0    xyz@gmail.com  
1    yxz@yahoo.com  
2    aaa@gmail.com  
3  jammy@gamil.com  
4  jammy@gamil.com

In [142]:
df2 = df2.drop(labels = [4])
df2

Salutation Name  Age     Sex    Location Marital Status    Phone  \
0         Dr  Sam   32    male     Atlanta       Divorced  1111111   
1         Dr  Pam   45  female     Georgia       Divorced  2222222   
2         Ms  Tam   12  female     Georgia         Single  3333333   
3         Mr  Jam   45    male  New Jersey        Married    99999   

             Email  
0    xyz@gmail.com  
1    yxz@yahoo.com  
2    aaa@gmail.com  
3  jammy@gamil.com

In [ ]:
#### Coursesa training on numpy

In [1]:
import numpy as np

In [3]:
one_d_array = np.array([10,12])
print(one_d_array)

[10 12]


In [32]:
# 1 Dimensional array
a = np.array([12,11,10])
print(f"1-D array using array function {a}")
b = np.arange(5)
print(f"1-D array using range [range of 5] {b}")
c = np.arange(1,20,3)
print(f"1-D array using range starting from 1 and ending 20 with increment 3 {c}")
d = np.linspace(0,100,5)
print(f"1-D array 5 evenly spaced elements from 0 to 100 which is float {d}")
e = np.linspace(0,100,5,dtype=int)
print(f"1-D array 5 evenly spaced elements from 0 to 100 which is integer {e}")
f = np.arange(1,20,3,dtype=float)
print(f"1-D array using range starting from 1 and ending 20 with increment 3 {f}")
char_arr = np.array(['Welcome to Math for ML!'])
print(char_arr)
print(char_arr.dtype)

1-D array using array function [12 11 10]
1-D array using range [range of 5] [0 1 2 3 4]
1-D array using range starting from 1 and ending 20 with increment 3 [ 1  4  7 10 13 16 19]
1-D array 5 evenly spaced elements from 0 to 100 which is float [  0.  25.  50.  75. 100.]
1-D array 5 evenly spaced elements from 0 to 100 which is integer [  0  25  50  75 100]
1-D array using range starting from 1 and ending 20 with increment 3 [ 1.  4.  7. 10. 13. 16. 19.]
['Welcome to Math for ML!']
<U23


In [31]:
ones_arr = np.ones(5,dtype=int)
print(f"1-D array of 1 created using [ones] {ones_arr}")
zero_arr = np.zeros(5,dtype=float)
print(f"1-D array of 0 created using [zeros] {zero_arr}")
empty_arr = np.empty(5,dtype=int) #returns 0 as zeros array
print(f"1-D empty created using [empty] {empty_arr}")
rand_arr = np.random.rand(5)
print(f"1-D array created using random generator {rand_arr}")

1-D array of 1 created using [ones] [1 1 1 1 1]
1-D array of 0 created using [zeros] [0. 0. 0. 0. 0.]
1-D empty created using [empty] [0 0 0 0 0]
1-D array created using random generator [0.8264669  0.3667887  0.83113252 0.97461261 0.85595117]


In [35]:
two_d_array = np.array([[11,12,13], [22,33,44]])
print(f"2-D array created using [array] {two_d_array}")
two_d_array

2-D array created using [array] [[11 12 13]
 [22 33 44]]


array([[11, 12, 13],
       [22, 33, 44]])

In [38]:
one_d_array   = np.array([1,2,3,4,5,6])
print(f"1-D array created using [array] {one_d_array} \n that can be convereted to M-D as below")
multi_d_array = np.reshape(one_d_array, (2,3))
print(f"M-D array created using [reshape] {multi_d_array}")
multi_d_array

1-D array created using [array] [1 2 3 4 5 6] 
 that can be convereted to M-D as below
M-D array created using [reshape] [[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
print(f"Dimesion of array {multi_d_array.ndim}") #returns 2 for 2-D array

Dimesion of array 2


In [41]:
print(f"Shape of array {multi_d_array.shape}") #returns (tuple) number of rows & columns (row,column)

Shape of array (2, 3)


In [42]:
print(f"Size of array {multi_d_array.size}") #returns number of elements in the array

Size of array 6


In [44]:
arr_1    = np.array([2,4,6])
arr_2    = np.array([1,3,5])
addition = arr_1 + arr_2
print(f"The sum of 2 arrays {arr_1} and {arr_2} is {addition}")

The sum of 2 arrays [2 4 6] and [1 3 5] is [ 3  7 11]


In [45]:
arr_1      = np.array([2,4,6])
arr_2      = np.array([1,3,5])
difference = arr_1 - arr_2
print(f"The difference of 2 arrays {arr_1} and {arr_2} is {difference}")

The difference of 2 arrays [2 4 6] and [1 3 5] is [1 1 1]


In [46]:
arr_1   = np.array([2,4,6])
arr_2   = np.array([1,3,5])
product = arr_1 * arr_2
print(f"The product of 2 arrays {arr_1} and {arr_2} is {product}")

The product of 2 arrays [2 4 6] and [1 3 5] is [ 2 12 30]


In [52]:
v = np.array([1,2])
miles_to_kms = v * 1.6
print(f"The miles to mks conversion for array {v} is {miles_to_kms}")

The miles to mks conversion for array [1 2] is [1.6 3.2]


In [58]:
print(f"The first element of 1-D array {a} is {a[0]}")
print(f"The second element of 1-D array {a} is {a[1]}")
print(f"The third element of 1-D array {a} is {a[2]}")

The first element of array [12 11 10] is 12
The second element of array [12 11 10] is 11
The third element of array [12 11 10] is 10


In [60]:
print(f"The first row of M-D array {multi_d_array} is {multi_d_array[0]}")
print(f"The second row of M-D array {multi_d_array} is {multi_d_array[1]}")

The first element of M-D array [[1 2 3]
 [4 5 6]] is [1 2 3]
The second element of M-D array [[1 2 3]
 [4 5 6]] is [4 5 6]


In [61]:
print(f"The first element in 1st row of M-D array {multi_d_array} is {multi_d_array[0][0]}")
print(f"The second element in 1st row of M-D array {multi_d_array} is {multi_d_array[0][1]}")

The first element in 1st row of M-D array [[1 2 3]
 [4 5 6]] is 1
The second element in 1st row of M-D array [[1 2 3]
 [4 5 6]] is 2


In [62]:
print(f"The element in 1st row and 2nd column of M-D array {multi_d_array} is {multi_d_array[1][2]}")

The element in 1st row and 2nd column of M-D array [[1 2 3]
 [4 5 6]] is 6


In [79]:
sl_a = np.array([1,2,3,4,5,6])
sliced_arr = sl_a[1:4]
print(f"The sliced array [1 to 4] of {sl_a} is {sliced_arr}")
sliced_arr_2 = sl_a[: : 2]
print(f"The sliced array [1 to 4] of {sl_a} in step 2  is {sliced_arr_2}")
print(sl_a[:])
print(sl_a[::])

The sliced array [1 to 4] of [1 2 3 4 5 6] is [2 3 4]
The sliced array [1 to 4] of [1 2 3 4 5 6] in step 2  is [1 3 5]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [82]:
multi_d_array

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
m_array = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [84]:
m_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
print(m_array[::,0])

[1 4 7]


In [94]:
a1 = np.array(([1,1],[2,2]))
a2 = np.array(([3,3],[4,4]))
print(a1)
print(a2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [109]:
v_stack = np.vstack((a1,a2))
h_stack = np.hstack((a1,a2))
print(f"Result of vertical stack of {a1} and {a2} is {v_stack}")
print(f"Result of horizontal stack of {a1} and {a2} is {h_stack}")
split_array = np.split(h_stack,2)
print(f"The split of {h_stack} is {split_array}")
h_split_array = np.hsplit(h_stack,4)
print(f"The horizontal split of {h_stack} is {h_split_array}")
h_split_array

Result of vertical stack of [[1 1]
 [2 2]] and [[3 3]
 [4 4]] is [[1 1]
 [2 2]
 [3 3]
 [4 4]]
Result of horizontal stack of [[1 1]
 [2 2]] and [[3 3]
 [4 4]] is [[1 1 3 3]
 [2 2 4 4]]
The split of [[1 1 3 3]
 [2 2 4 4]] is [array([[1, 1, 3, 3]]), array([[2, 2, 4, 4]])]
The horizontal split of [[1 1 3 3]
 [2 2 4 4]] is [array([[1],
       [2]]), array([[1],
       [2]]), array([[3],
       [4]]), array([[3],
       [4]])]


[array([[1],
        [2]]),
 array([[1],
        [2]]),
 array([[3],
        [4]]),
 array([[3],
        [4]])]

In [110]:
h_stack

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [12]:
import numpy as np

In [16]:
A = np.array(([-1,3],[3,2]), dtype=np.dtype(float))
b = np.array([7,1], dtype=np.dtype(float))

In [17]:
print(A)
print(b)

[[-1.  3.]
 [ 3.  2.]]
[7. 1.]


In [19]:
print(f"The shape of matrix {A} is {A.shape}")
print(f"The share of vector {b} is {b.shape}")

The shape of matrix [[-1.  3.]
 [ 3.  2.]] is (2, 2)
The share of vector [7. 1.] is (2,)


In [29]:
x = np.linalg.solve(A,b)
print(f"The value of x1 is {x[0]} and value of x2 is {x[1]} for the matrix {A}")

The value of x1 is -1.0 and value of x2 is 2.0 for the matrix [[-1.  3.]
 [ 3.  2.]]


In [33]:
y = np.linalg.det(A)
print(f"The determinant of matrix {A} is {y:.2f}")

The determinant of matrix [[-1.  3.]
 [ 3.  2.]] is -11.00


In [39]:
l_e = np.hstack((A,b.reshape(2,1)))
l_e

array([[-1.,  3.,  7.],
       [ 3.,  2.,  1.]])

In [40]:
print(l_e[1])

[3. 2. 1.]


In [43]:
A_2 = np.array(([-1,3],[3,-9]),dtype=np.dtype(float))
b_2 = np.array([7,1], dtype=np.dtype(float))

y_2 = np.linalg.det(A_2)
print(f"The determinant of matrix {A} is {y_2:.2f}")

The determinant of matrix [[-1.  3.]
 [ 3.  2.]] is 0.00


In [44]:
try:
    x_2 = np.linalg.solve(A_2, b_2)
except np.linalg.LinAlgError as err:
    print(err)

Singular matrix


In [45]:
l_e_2 = np.hstack((A_2, b_2.reshape(2,1)))
l_e_2

array([[-1.,  3.,  7.],
       [ 3., -9.,  1.]])

In [46]:
#A_3 = np.array(([-1,3],[3,-9]), dtype=np.dtype(float))
b_3 = np.array([7, -21], dtype=np.dtype(float))

A_3 = np.hstack((A_2, b_3.reshape(2,1)))

A_3

array([[ -1.,   3.,   7.],
       [  3.,  -9., -21.]])

In [51]:
try:
    x_3 = np.linalg.solve(A_2, b_3)
except np.linalg.LinAlgError as err:
    print(err)

Singular matrix


In [53]:
y_3 = np.linalg.det(A_2)
print(f"The determinant of matrix {A_3} is {y_3:.2f}")

The determinant of matrix [[ -1.   3.   7.]
 [  3.  -9. -21.]] is 0.00


In [54]:
A_4 = np.array(([1,2,1],[2,1,1],[-1,2,1]))
y_4 = np.linalg.det(A_4)
y_4

np.float64(-2.000000000000001)

In [55]:
A_5 = np.array(([1,2,3],[3,2,1],[2,2,1]))
y_5 = np.linalg.det(A_5)
y_5

np.float64(4.000000000000001)

In [56]:
A_6 = np.array(([1,2,3],[0,2,2],[1,4,5]))
y_6 = np.linalg.det(A_6)
y_6

np.float64(0.0)

In [4]:
N = np.array([
[0, 5, -3 ,6 ,8],
[0, 6, 3, 8, 1],
[0, 0, 0, 0, 0],
[0, 0, 0 ,0 ,7],
[0, 2, 1, 0, 4]
]
)
print(N)

[[ 0  5 -3  6  8]
 [ 0  6  3  8  1]
 [ 0  0  0  0  0]
 [ 0  0  0  0  7]
 [ 0  2  1  0  4]]


In [22]:
p_c = N[0,0]
print(p_c)

0


In [7]:
np.isclose(p_c,0)

array([[ True, False, False, False, False]])

In [14]:
c_1 = N[0:,1]
c_1

array([5, 6, 0, 0, 2])

In [15]:
np.isclose(c_1, 0, atol=1e-8)

array([False, False,  True,  True, False])

In [17]:
N_swap = N.copy()
N_swap[[0,2]] = N[[2,0]]
N_swap

array([[ 0,  0,  0,  0,  0],
       [ 0,  6,  3,  8,  1],
       [ 0,  5, -3,  6,  8],
       [ 0,  0,  0,  0,  7],
       [ 0,  2,  1,  0,  4]])

In [23]:
if np.isclose(p_c, 0) == True:
    col_array = N[0:,0]
    col_array

In [26]:
for j in range(2):
    print(j)

0
1


In [29]:
newN = np.array(([1,2,3],[2,6,12],[4,-8,4]))
newN

array([[ 1,  2,  3],
       [ 2,  6, 12],
       [ 4, -8,  4]])

In [30]:
newN_d = np.linalg.det(newN)
newN_d

np.float64(80.00000000000004)

In [31]:
from utils import string_to_augmented_matrix

ImportError: cannot import name 'string_to_augmented_matrix' from 'utils' (C:\Users\AW954XQ\utils\__init__.py)

In [3]:
import numpy as np

In [2]:
N

NameError: name 'N' is not defined

In [36]:
NN = N.copy()

In [37]:
NN

array([[ 0,  5, -3,  6,  8],
       [ 0,  6,  3,  8,  1],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  7],
       [ 0,  2,  1,  0,  4]])

In [38]:
NN[[3,4]] = NN[[4,3]]
NN

array([[ 0,  5, -3,  6,  8],
       [ 0,  6,  3,  8,  1],
       [ 0,  0,  0,  0,  0],
       [ 0,  2,  1,  0,  4],
       [ 0,  0,  0,  0,  7]])

In [40]:
print(NN[3,4])

4


In [41]:
NN[0:,2]

array([-3,  3,  0,  1,  0])

In [5]:
N

array([[ 0,  5, -3,  6,  8],
       [ 0,  6,  3,  8,  1],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  7],
       [ 0,  2,  1,  0,  4]])

In [7]:
N[0:,2]

array([-3,  3,  0,  0,  1])

In [8]:
N[2:,2]

array([0, 0, 1])

In [15]:
N.shape[1]

5

In [13]:
N.shape

(5, 5)

In [17]:
NN = np.array([[6,4,8,1],[0,8,6,4],[0,0,0,3],[0,0,5,9]])

In [18]:
NN

array([[6, 4, 8, 1],
       [0, 8, 6, 4],
       [0, 0, 0, 3],
       [0, 0, 5, 9]])

In [19]:
NN[2]

array([0, 0, 0, 3])

In [23]:
print(NN[2,3])

3


In [26]:
NN[[2,2]] = NN[[3,2]]
NN

array([[6, 4, 8, 1],
       [0, 8, 6, 4],
       [0, 0, 0, 3],
       [0, 0, 5, 9]])

In [27]:
import numpy as np
import matplotlib as plt

In [29]:
def plot_vectors(list_v, list_label, list_color):
    _, ax = plt.subplots(figsize=(10,10))
    ax.tick_params(axis='x', labelsize=14)
    ax.tick_params(axis='y', labelsize=14)
    ax.set_xticks(np.arange(-10,10))
    ax.set_ytricks(np.arange(-10,10))

    plt.axis([-10, 10, -10, 10])
    for i, v in enumerate(list_v):
        sgn = 0.4 * np.array([[1] if i==0 else [i] for i in np.sign(v)])
        plt.quiver(v[0], v[1], color=list_color[i], angles='xy', scale_units='xy', scale=1)
        ax.text(v[0]-0.2+sgn[0], v[1]-0.2+sgn[1], list_label[i], fontsize=14, color=list_color[i])

    plt.grid()
    plt.gca().set_aspect("equal")
    plt.show()

v = np.array([[1], [3]])
plot_vectors([v], [f"$v$"], ["black"])

AttributeError: module 'matplotlib' has no attribute 'subplots'

In [36]:
x = [1, -2, -5]
y = [4, 3, -1]
result = 0

for a, b in zip(x,y):
    result+= a * b

print(result)

3


In [40]:
a = [1, -2, -5]
b = [4, 3, -1]
print('Dot:', np.dot(a,b))
print('Add:', np.add(a,b))
print('Norm:', np.linalg.norm(a))
print('Norm:', np.linalg.norm(b))

Dot: 3
Add: [ 5  1 -6]
Norm: 5.477225575051661
Norm: 5.0990195135927845


In [41]:
x = [3,1]
y = [1,0]
print(np.dot(x,y))

3


In [45]:
x = [[3,1],[1,2]]
y = [1,1]
print(np.dot(x,y))

[4 3]


In [1]:
import numpy as np

In [7]:
x = np.array([1, -2, -5])
y = np.array([4, 3, -1])
print(y)
print(y.reshape(3,1).shape)
print(np.matmul(x,y))

[ 4  3 -1]
(3, 1)
3


In [9]:
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

In [17]:
# T(v) = w
# T[v1,v2] = [3v1, 0, -2v2]
def T(v):
    w = np.zeros((3,1))
    w[0,0] = 3*v[0,0]
    w[2,0] = -2*v[1,0]
    return w

v = np.array([[1,0],[0,1]])
w = T(v)
print(w)

[[3.]
 [0.]
 [0.]]


In [15]:
v1 = np.array([[2],[4]])

k = 2

print('k*v1:', k*v1)
print('T(k*v1):', T(k*v1))
print('k*T(v1):', k*T(v1))

k*v1: [[4]
 [8]]
T(k*v1): [[ 12.]
 [  0.]
 [-16.]]
k*T(v1): [[ 12.]
 [  0.]
 [-16.]]


In [16]:
u1 = np.array([[1],[-2]])
print('T(u1+v1):', T(u1+v1))
print('T(u1)+T(v1):', T(u1)+T(v1))

T(u1+v1): [[ 9.]
 [ 0.]
 [-4.]]
T(u1)+T(v1): [[ 9.]
 [ 0.]
 [-4.]]
